name: Downloader by Aria2

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      Url:
        description: 'Download Url'
        required: false
        default: 'false'
#   watch:
#     types: started
env:
  FILE_PATH: 'downloads'
  
jobs:

  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 
    - name: Aria2 Install
      run: sudo apt install -y aria2


    - name: Downloading
      id: downloading
      run: |
        url=$(cat url)
        filename=${url##*##}
        download=${url%##*}
        echo "::set-output name=path::downloads/$filename"
        echo "::set-output name=filename::$filename"
        aria2c --conf $GITHUB_WORKSPACE/aria2.conf --seed-time=0 -d downloads -c $downloadurl -o $filename


    - uses: ykxVK8yL5L/add-to-web3@v1.3
      id: web3
      with:
        web3_token: ${{ secrets.WEB3_STORAGE_TOKEN }}
        path_to_add: ${{ steps.downloading.outputs.path }} 
        file_name: ${{ steps.downloading.outputs.filename }} 
        wrap_with_directory: true
    - run: echo ${{ steps.web3.outputs.url }}
