name: Downloader by Aria2

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      Url:
        description: 'Download Url'
        required: false
        default: 'false'
#   watch:
#     types: started

jobs:

  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 
    - name: Aria2 Install
      run: sudo apt install -y aria2
    - name: Inject Aria2 config
      run: |
        mkdir -p ~/.aria2/
        cat >  ~/.aria2/aria2.conf  << EOF
        ${{ secrets.ARIA2_CONF }}
        EOF

    - name: Downloading
      run: |
        url=${{secrets.DOWNLOAD }}
        filename=${url##*##}
        download=${url%##*}
        aria2c --seed-time=0 -d downloads -c $download -o $filename

    - uses: web3-storage/add-to-web3@v1
      id: web3
      with:
        web3_token: ${{ secrets.WEB3_STORAGE_TOKEN }}
        path_to_add: downloads/$filename
    - run: echo ${{ steps.web3.outputs.url }}/$filename
