name: 1Download task

on:
    workflow_dispatch:
#    schedule:
#     - cron: "*/20 * * * *"
#   watch:
#     types: started
env:
  FILE_PATH: 'downloads'
  
jobs:

  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 
    - name: Aria2 Install
      run: sudo apt install -y aria2 

    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: install prerequisites
      run: |
        python -m pip install --upgrade pip wheel
        pip install install lk21==1.5.61 pymongo pymongo[srv] pymongo[tls] certifi
    
    - name: Get Download Url
      id: geturl
      run: |
        url=$(python task.py  --con="${{ secrets.DB_CONNECT }}")
        echo "::set-output name=fileurl::$url"
      
      
    - name: Downloading
      id: downloading
      if: steps.geturl.outputs.fileurl != 'None' && !cancelled()
      run: |
        url=${{ steps.geturl.outputs.fileurl }} 
        filename=${url##*##}
        download=${url%##*}
         downloadurl=$(python get_url.py --url="$download")
        echo "::set-output name=path::downloads/$filename"
        echo "::set-output name=filename::$filename"
        aria2c --conf $GITHUB_WORKSPACE/aria2.conf --seed-time=0 -d downloads -c $downloadurl -o $filename
        result=$(python uptonft.py --token="" --path="downloads/$filename")
        echo $result


  
