name: test

on:
  workflow_call:
  repository_dispatch:
  workflow_dispatch:
    inputs:
env:
  FILE_PATH: 'downloads'
  
jobs:

  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: ./.github/workflows/test.yml
      
