name: test dispatch actions

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:

jobs:

  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: ./.github/workflows/test.yml
