name: test

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
env:
  FILE_PATH: 'downloads'
  
jobs:

  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false 
        fetch-depth: 0 

    - uses: ./.github/workflows/test.yml
