name: test

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
env:
  FILE_PATH: 'downloads'
  
jobs:

  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 
   
    - name: start another test
      uses: benc-uk/workflow-dispatch@v1
      if:  !cancelled() && !failure()
      with:
        workflow: test
        token: ${{ secrets.TOKEN }}
      
