name: 00Youtube转存Rclone
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      download_url:
        description: '下载网址'
        required: true
        default: ''

jobs:
  Download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup yt-dlp
        uses: AnimMouse/setup-yt-dlp@v1
        with:
          with-ffmpeg: true
      - name: 'Download Video' 
        run: |
          mkdir out
          cd out
          yt-dlp -f bestvideo+bestaudio -S -4 ext:mp4:m4a --downloader aria2c ${{ github.event.inputs.download_url }}

      - name: Downloading
        id: downloading
        run: |
          filename=$(ls out | head -n1)
          echo "::set-output name=path::out/$filename"
          echo "::set-output name=filename::$filename"
          size=$(ls -l 'out/$filename' | awk '{print $5}' )
          echo $filename
          echo "::set-output name=size::$size"

      - name: 上传到Cloudreve
        id: webdav
        if: steps.downloading.outputs.filename != '' && !cancelled() && !failure()
        run: |
          python webdav_user.py --name="hefamily" --projet="${{ secrets.DETA_PROJECT_ID }}" --apikey="${{ secrets.DETA_API_KEY }}" --filename="${{ steps.downloading.outputs.filename }}" --filepath="/files2"

        


