name: Youtube转存Rclone
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      download_url:
        description: '下载网址'
        required: true
        default: 'https://www.youtube.com/watch?v=q0hyYWKXF0Q'

jobs:
  Onedriver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup yt-dlp
        uses: AnimMouse/setup-yt-dlp@v1
        with:
          with-ffmpeg: true
      - name: 'Download Video' 
        run: |
          mkdir videos
          cd videos
          yt-dlp --downloader aria2c ${{ github.event.inputs.download_url }}
            
      - name: rclone
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: copy videos cloud:videos
        


