name: ZDownload youtube by input
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      Url:
        description: 'Download Url'
        required: false
        default: 'false'
#   watch:
#     types: started
env:
  FILE_PATH: 'downloads'
jobs:
  youtubedownload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false 
        fetch-depth: 0 
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: install prerequisites
      run: |
        python -m pip install --upgrade pip wheel
        pip install install requests cloudscraper pymongo pymongo[srv] pymongo[tls] certifi
        
    - name: Setup yt-dlp
      uses: AnimMouse/setup-yt-dlp@v1
      with:
        with-ffmpeg: true
      
    - name: Downloading
      id: downloading
      run: |
        url="${{ github.event.inputs.Url}}"
        filename=${url##*##}
        download=${url%##*}
        mkdir video
        yt-dlp --downloader aria2c -f 137+140 -o "video/$filename"  $download
        size=$(ls -l video/$filename | awk '{print $5}' )
        filename=$(yt-dlp -f 137+140 --get-filename -o "video/$filename" $download)
        echo "::set-output name=path::video/"
        echo "::set-output name=filename::$filename"
        echo "::set-output name=size::$size"
        
        
#     - name: Downloading
#       id: downloading
#       run: |
#         url="${{ github.event.inputs.Url}}"
#         downloadurl="$download"
#         mkdir video
#         yt-dlp --downloader aria2c -f 137+140 -o "video/%(title)s.%(ext)s"  $url
#         size=$(ls -l video/$filename | awk 'NR == 2' | awk '{print $5}' )
#         filename=$(yt-dlp -f 137+140 --get-filename -o "video/%(title)s.%(ext)s" $url)
#         echo "::set-output name=path::$filename"
#         echo "::set-output name=filename::$filename"
#         echo "::set-output name=size::$size"

    - name: Save Data    
      uses: web3-storage/add-to-web3@v2
      id: web3
      with:
        web3_token: ${{ secrets.WEB3_STORAGE_TOKEN }}
        path_to_add: 'video'
        
    - name: Save Data
      id:  database
      if: steps.downloading.outputs.filename != '' && !cancelled() && !failure()
      run: |
        python save.py --con="${{ secrets.DB_CONNECT }}" --name="${{ steps.downloading.outputs.filename }}" --size="${{ steps.downloading.outputs.size }}" --cid="${{ steps.web3.outputs.cid }}"
        echo "::set-output name=status::ok"


    - name: Notify upload info to mqtt broker
      if: steps.database.outputs.status != '' && !cancelled() && !failure()
      uses: juhrlass/mqtt-action@master
      with:
        protocol: mqtt
        host: broker-cn.emqx.io
        port: 1883
        topic: ${{ secrets.SYNC_TOPIC }}
        message: 'ok'
        username: ''
        password: ''

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 0
