name: ZDownload youtube upload mayiyun
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      Url:
        description: 'Download Url'
        required: false
        default: 'false'
#   watch:
#     types: started
env:
  FILE_PATH: 'downloads'
jobs:
  youtubedownload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false 
        fetch-depth: 0 
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: install prerequisites
      run: |
        python -m pip install --upgrade pip wheel
        pip install install requests cloudscraper pymongo pymongo[srv] pymongo[tls] certifi
        
    - name: Setup yt-dlp
      uses: AnimMouse/setup-yt-dlp@v1
      with:
        with-ffmpeg: true
      
    - name: Downloading
      id: downloading
      run: |
        url="${{ github.event.inputs.Url}}"
        filename=${url##*##}
        download=${url%##*}
        mkdir video
        yt-dlp --downloader aria2c -f 137+140 -o "video/$filename"  $download
        size=$(ls -l "video/$filename" | awk '{print $5}' )
        echo "::set-output name=filename::$filename"
        echo "::set-output name=path::video/$filename"
        echo "::set-output name=size::$size"
        
    - uses: bxb100/action-upload-webdav@v1
      with:
        webdav_address: ${{secrets.WEBDAV_ADDRESS}}
        webdav_username: ${{secrets.WEBDAV_USERNAME}}
        webdav_password: ${{secrets.WEBDAV_PASSWORD}}
        webdav_upload_path: "/"
        files: "./video/${{ steps.downloading.outputs.filename }}"

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 0
